# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 07:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0002_address_education_insignia_personalinfo_workinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=70, verbose_name='อำเภอ(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district_regis',
            field=models.CharField(max_length=70, verbose_name='อำเภอ(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='lane',
            field=models.CharField(max_length=40, verbose_name='ซอย(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='lane_regis',
            field=models.CharField(max_length=40, verbose_name='ซอย(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=10, verbose_name='เลขที่(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number_regis',
            field=models.CharField(max_length=10, verbose_name='เลขที่(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='เบอร์โทรบ้าาน(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number_regis',
            field=models.CharField(max_length=20, verbose_name='เบอร์โทรบ้าาน(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.IntegerField(default=0, verbose_name='รหัสไปรษณีย์(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code_regis',
            field=models.IntegerField(default=0, verbose_name='รหัสไปรษณีย์(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=70, verbose_name='จังหวัด(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province_regis',
            field=models.CharField(max_length=70, verbose_name='จังหวัด(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='road',
            field=models.CharField(max_length=70, verbose_name='ถนน(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='road_regis',
            field=models.CharField(max_length=70, verbose_name='ถนน(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='smartphone_number',
            field=models.CharField(max_length=20, verbose_name='เบอร์มือถือ(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='smartphone_number_regis',
            field=models.CharField(max_length=20, verbose_name='เบอร์มือถือ(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='sub_district',
            field=models.CharField(max_length=70, verbose_name='ตำบล(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='sub_district_regis',
            field=models.CharField(max_length=70, verbose_name='ตำบล(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='village_name',
            field=models.CharField(max_length=40, verbose_name='หมู่บ้าน(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='village_name_regis',
            field=models.CharField(max_length=40, verbose_name='หมู่บ้าน(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='village_no',
            field=models.IntegerField(default=0, verbose_name='หมู่(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='village_no_regis',
            field=models.IntegerField(default=0, verbose_name='หมู่(ตามทะเบียนบ้าน)'),
        ),
    ]
