# Generated by Django 2.0 on 2017-12-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20171023_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_year_bachelor',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year_master',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year_phD',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year_bachelor',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year_master',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year_phD',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='insignia',
            name='class1',
            field=models.CharField(max_length=60, verbose_name='ชั้น'),
        ),
        migrations.AlterField(
            model_name='insignia',
            name='date1',
            field=models.DateField(blank=True, null=True, verbose_name='วัน/เดือน/ปี ที่ได้รับ'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='วัน/เดือน/ปี เกิด'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='status',
            field=models.CharField(choices=[('MR', 'แต่งงาน'), ('SN', 'โสด'), ('DV', 'หย่า'), ('WD', 'หม้าย')], max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='end_service_date',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='start_PW_date',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='start_service_date',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
