# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20171209_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='father_title',
            field=models.CharField(blank=True, choices=[('MR', 'Mr.(นาย)'), ('MRS', 'Mrs.(นาง)'), ('MISS', 'Miss.(นางสาว)')], default='MR', max_length=6),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='mother_title',
            field=models.CharField(blank=True, choices=[('MR', 'Mr.(นาย)'), ('MRS', 'Mrs.(นาง)'), ('MISS', 'Miss.(นางสาว)')], default='MR', max_length=6),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='spouse_title',
            field=models.CharField(blank=True, choices=[('MR', 'Mr.(นาย)'), ('MRS', 'Mrs.(นาง)'), ('MISS', 'Miss.(นางสาว)')], default='MR', max_length=6),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=70, verbose_name='อำเภอ(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district_regis',
            field=models.CharField(blank=True, max_length=70, verbose_name='อำเภอ(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='lane',
            field=models.CharField(blank=True, max_length=40, verbose_name='ซอย(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='lane_regis',
            field=models.CharField(blank=True, max_length=40, verbose_name='ซอย(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, max_length=10, verbose_name='เลขที่(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number_regis',
            field=models.CharField(blank=True, max_length=10, verbose_name='เลขที่(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทรบ้าน(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number_regis',
            field=models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทรบ้าาน(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='รหัสไปรษณีย์(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code_regis',
            field=models.CharField(blank=True, max_length=10, verbose_name='รหัสไปรษณีย์(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, choices=[('กรุงเทพมหานคร', 'กรุงเทพมหานคร'), ('กระบี่', 'กระบี่'), ('กาญจนบุรี', 'กาญจนบุรี'), ('กาฬสินธุ์', 'กาฬสินธุ์'), ('กำแพงเพชร', 'กำแพงเพชร'), ('ขอนแก่น', 'ขอนแก่น'), ('จันทบุรี', 'จันทบุรี'), ('ฉะเชิงเทรา', 'ฉะเชิงเทรา'), ('ชลบุรี', 'ชลบุรี'), ('ชัยนาท', 'ชัยนาท'), ('ชัยภูมิ', 'ชัยภูมิ'), ('ชุมพร', 'ชุมพร'), ('เชียงราย', 'เชียงราย'), ('เชียงใหม่', 'เชียงใหม่'), ('ตรัง', 'ตรัง'), ('ตราด', 'ตราด'), ('ตาก', 'ตาก'), ('นครนายก', 'นครนายก'), ('นครปฐม', 'นครปฐม'), ('นครพนม', 'นครพนม'), ('นครราชสีมา', 'นครราชสีมา'), ('นครศรีธรรมราช', 'นครศรีธรรมราช'), ('นครสวรรค์', 'นครสวรรค์'), ('นนทบุรี', 'นนทบุรี'), ('นราธิวาส', 'นราธิวาส'), ('น่าน', 'น่าน'), ('บึงกาฬ', 'บึงกาฬ'), ('บุรีรัมย์', 'บุรีรัมย์'), ('ปทุมธานี', 'ปทุมธานี'), ('ประจวบคีรีขันธ์', 'ประจวบคีรีขันธ์'), ('ปราจีนบุรี', 'ปราจีนบุรี'), ('ปัตตานี', 'ปัตตานี'), ('พระนครศรีอยุธยา', 'พระนครศรีอยุธยา'), ('พังงา', 'พังงา'), ('พัทลุง', 'พัทลุง'), ('พิจิตร', 'พิจิตร'), ('พิษณุโลก', 'พิษณุโลก'), ('เพชรบุรี', 'เพชรบุรี'), ('เพชรบูรณ์', 'เพชรบูรณ์'), ('แพร่', 'แพร่'), ('พะเยา', 'พะเยา'), ('ภูเก็ต', 'ภูเก็ต'), ('มหาสารคาม', 'มหาสารคาม'), ('มุกดาหาร', 'มุกดาหาร'), ('แม่ฮ่องสอน', 'แม่ฮ่องสอน'), ('ยะลา', 'ยะลา'), ('ยโสธร', 'ยโสธร'), ('ร้อยเอ็ด', 'ร้อยเอ็ด'), ('ระนอง', 'ระนอง'), ('ระยอง', 'ระยอง'), ('ราชบุรี', 'ราชบุรี'), ('ลพบุรี', 'ลพบุรี'), ('ลำปาง', 'ลำปาง'), ('ลำพูน', 'ลำพูน'), ('เลย', 'เลย'), ('ศรีสะเกษ', 'ศรีสะเกษ'), ('สกลนคร', 'สกลนคร'), ('สงขลา', 'สงขลา'), ('สตูล', 'สตูล'), ('สมุทรปราการ', 'สมุทรปราการ'), ('สมุทรสงคราม', 'สมุทรสงคราม'), ('สมุทรสาคร', 'สมุทรสาคร'), ('สระแก้ว', 'สระแก้ว'), ('สระบุรี', 'สระบุรี'), ('สิงห์บุรี', 'สิงห์บุรี'), ('สุโขทัย', 'สุโขทัย'), ('สุพรรณบุรี', 'สุพรรณบุรี'), ('สุราษฎร์ธานี', 'สุราษฎร์ธานี'), ('สุรินทร์', 'สุรินทร์'), ('หนองคาย', 'หนองคาย'), ('หนองบัวลำภู', 'หนองบัวลำภู'), ('อ่างทอง', 'อ่างทอง'), ('อุดรธานี', 'อุดรธานี'), ('อุทัยธานี', 'อุทัยธานี'), ('อุตรดิตถ์', 'อุตรดิตถ์'), ('อุบลราชธานี', 'อุบลราชธานี'), ('อำนาจเจริญ', 'อำนาจเจริญ')], max_length=70, verbose_name='จังหวัด(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province_regis',
            field=models.CharField(blank=True, choices=[('กรุงเทพมหานคร', 'กรุงเทพมหานคร'), ('กระบี่', 'กระบี่'), ('กาญจนบุรี', 'กาญจนบุรี'), ('กาฬสินธุ์', 'กาฬสินธุ์'), ('กำแพงเพชร', 'กำแพงเพชร'), ('ขอนแก่น', 'ขอนแก่น'), ('จันทบุรี', 'จันทบุรี'), ('ฉะเชิงเทรา', 'ฉะเชิงเทรา'), ('ชลบุรี', 'ชลบุรี'), ('ชัยนาท', 'ชัยนาท'), ('ชัยภูมิ', 'ชัยภูมิ'), ('ชุมพร', 'ชุมพร'), ('เชียงราย', 'เชียงราย'), ('เชียงใหม่', 'เชียงใหม่'), ('ตรัง', 'ตรัง'), ('ตราด', 'ตราด'), ('ตาก', 'ตาก'), ('นครนายก', 'นครนายก'), ('นครปฐม', 'นครปฐม'), ('นครพนม', 'นครพนม'), ('นครราชสีมา', 'นครราชสีมา'), ('นครศรีธรรมราช', 'นครศรีธรรมราช'), ('นครสวรรค์', 'นครสวรรค์'), ('นนทบุรี', 'นนทบุรี'), ('นราธิวาส', 'นราธิวาส'), ('น่าน', 'น่าน'), ('บึงกาฬ', 'บึงกาฬ'), ('บุรีรัมย์', 'บุรีรัมย์'), ('ปทุมธานี', 'ปทุมธานี'), ('ประจวบคีรีขันธ์', 'ประจวบคีรีขันธ์'), ('ปราจีนบุรี', 'ปราจีนบุรี'), ('ปัตตานี', 'ปัตตานี'), ('พระนครศรีอยุธยา', 'พระนครศรีอยุธยา'), ('พังงา', 'พังงา'), ('พัทลุง', 'พัทลุง'), ('พิจิตร', 'พิจิตร'), ('พิษณุโลก', 'พิษณุโลก'), ('เพชรบุรี', 'เพชรบุรี'), ('เพชรบูรณ์', 'เพชรบูรณ์'), ('แพร่', 'แพร่'), ('พะเยา', 'พะเยา'), ('ภูเก็ต', 'ภูเก็ต'), ('มหาสารคาม', 'มหาสารคาม'), ('มุกดาหาร', 'มุกดาหาร'), ('แม่ฮ่องสอน', 'แม่ฮ่องสอน'), ('ยะลา', 'ยะลา'), ('ยโสธร', 'ยโสธร'), ('ร้อยเอ็ด', 'ร้อยเอ็ด'), ('ระนอง', 'ระนอง'), ('ระยอง', 'ระยอง'), ('ราชบุรี', 'ราชบุรี'), ('ลพบุรี', 'ลพบุรี'), ('ลำปาง', 'ลำปาง'), ('ลำพูน', 'ลำพูน'), ('เลย', 'เลย'), ('ศรีสะเกษ', 'ศรีสะเกษ'), ('สกลนคร', 'สกลนคร'), ('สงขลา', 'สงขลา'), ('สตูล', 'สตูล'), ('สมุทรปราการ', 'สมุทรปราการ'), ('สมุทรสงคราม', 'สมุทรสงคราม'), ('สมุทรสาคร', 'สมุทรสาคร'), ('สระแก้ว', 'สระแก้ว'), ('สระบุรี', 'สระบุรี'), ('สิงห์บุรี', 'สิงห์บุรี'), ('สุโขทัย', 'สุโขทัย'), ('สุพรรณบุรี', 'สุพรรณบุรี'), ('สุราษฎร์ธานี', 'สุราษฎร์ธานี'), ('สุรินทร์', 'สุรินทร์'), ('หนองคาย', 'หนองคาย'), ('หนองบัวลำภู', 'หนองบัวลำภู'), ('อ่างทอง', 'อ่างทอง'), ('อุดรธานี', 'อุดรธานี'), ('อุทัยธานี', 'อุทัยธานี'), ('อุตรดิตถ์', 'อุตรดิตถ์'), ('อุบลราชธานี', 'อุบลราชธานี'), ('อำนาจเจริญ', 'อำนาจเจริญ')], max_length=70, verbose_name='จังหวัด(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='road',
            field=models.CharField(blank=True, max_length=70, verbose_name='ถนน(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='road_regis',
            field=models.CharField(blank=True, max_length=70, verbose_name='ถนน(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='smartphone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='เบอร์มือถือ(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='smartphone_number_regis',
            field=models.CharField(blank=True, max_length=20, verbose_name='เบอร์มือถือ(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='sub_district',
            field=models.CharField(blank=True, max_length=70, verbose_name='ตำบล(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='sub_district_regis',
            field=models.CharField(blank=True, max_length=70, verbose_name='ตำบล(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='village_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='หมู่บ้าน(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='village_name_regis',
            field=models.CharField(blank=True, max_length=40, verbose_name='หมู่บ้าน(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='village_no',
            field=models.CharField(blank=True, max_length=10, verbose_name='หมู่(ปัจจุบัน)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='village_no_regis',
            field=models.CharField(blank=True, max_length=10, verbose_name='หมู่(ตามทะเบียนบ้าน)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='acronym_bachelor',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='education',
            name='acronym_master',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='education',
            name='acronym_phD',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='education',
            name='major_field_bachelor',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='education',
            name='major_field_master',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='education',
            name='major_field_phD',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='education',
            name='minor_field_bachelor',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='education',
            name='minor_field_master',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='education',
            name='minor_field_phD',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='education',
            name='university_bachelor',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='education',
            name='university_master',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='education',
            name='university_phD',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='insignia',
            name='class1',
            field=models.CharField(blank=True, max_length=60, verbose_name='ชั้น'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=6, verbose_name='กรุ๊ปเลือด'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='เลขบัตรประชาชน'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='domicile_province',
            field=models.CharField(blank=True, choices=[('กรุงเทพมหานคร', 'กรุงเทพมหานคร'), ('กระบี่', 'กระบี่'), ('กาญจนบุรี', 'กาญจนบุรี'), ('กาฬสินธุ์', 'กาฬสินธุ์'), ('กำแพงเพชร', 'กำแพงเพชร'), ('ขอนแก่น', 'ขอนแก่น'), ('จันทบุรี', 'จันทบุรี'), ('ฉะเชิงเทรา', 'ฉะเชิงเทรา'), ('ชลบุรี', 'ชลบุรี'), ('ชัยนาท', 'ชัยนาท'), ('ชัยภูมิ', 'ชัยภูมิ'), ('ชุมพร', 'ชุมพร'), ('เชียงราย', 'เชียงราย'), ('เชียงใหม่', 'เชียงใหม่'), ('ตรัง', 'ตรัง'), ('ตราด', 'ตราด'), ('ตาก', 'ตาก'), ('นครนายก', 'นครนายก'), ('นครปฐม', 'นครปฐม'), ('นครพนม', 'นครพนม'), ('นครราชสีมา', 'นครราชสีมา'), ('นครศรีธรรมราช', 'นครศรีธรรมราช'), ('นครสวรรค์', 'นครสวรรค์'), ('นนทบุรี', 'นนทบุรี'), ('นราธิวาส', 'นราธิวาส'), ('น่าน', 'น่าน'), ('บึงกาฬ', 'บึงกาฬ'), ('บุรีรัมย์', 'บุรีรัมย์'), ('ปทุมธานี', 'ปทุมธานี'), ('ประจวบคีรีขันธ์', 'ประจวบคีรีขันธ์'), ('ปราจีนบุรี', 'ปราจีนบุรี'), ('ปัตตานี', 'ปัตตานี'), ('พระนครศรีอยุธยา', 'พระนครศรีอยุธยา'), ('พังงา', 'พังงา'), ('พัทลุง', 'พัทลุง'), ('พิจิตร', 'พิจิตร'), ('พิษณุโลก', 'พิษณุโลก'), ('เพชรบุรี', 'เพชรบุรี'), ('เพชรบูรณ์', 'เพชรบูรณ์'), ('แพร่', 'แพร่'), ('พะเยา', 'พะเยา'), ('ภูเก็ต', 'ภูเก็ต'), ('มหาสารคาม', 'มหาสารคาม'), ('มุกดาหาร', 'มุกดาหาร'), ('แม่ฮ่องสอน', 'แม่ฮ่องสอน'), ('ยะลา', 'ยะลา'), ('ยโสธร', 'ยโสธร'), ('ร้อยเอ็ด', 'ร้อยเอ็ด'), ('ระนอง', 'ระนอง'), ('ระยอง', 'ระยอง'), ('ราชบุรี', 'ราชบุรี'), ('ลพบุรี', 'ลพบุรี'), ('ลำปาง', 'ลำปาง'), ('ลำพูน', 'ลำพูน'), ('เลย', 'เลย'), ('ศรีสะเกษ', 'ศรีสะเกษ'), ('สกลนคร', 'สกลนคร'), ('สงขลา', 'สงขลา'), ('สตูล', 'สตูล'), ('สมุทรปราการ', 'สมุทรปราการ'), ('สมุทรสงคราม', 'สมุทรสงคราม'), ('สมุทรสาคร', 'สมุทรสาคร'), ('สระแก้ว', 'สระแก้ว'), ('สระบุรี', 'สระบุรี'), ('สิงห์บุรี', 'สิงห์บุรี'), ('สุโขทัย', 'สุโขทัย'), ('สุพรรณบุรี', 'สุพรรณบุรี'), ('สุราษฎร์ธานี', 'สุราษฎร์ธานี'), ('สุรินทร์', 'สุรินทร์'), ('หนองคาย', 'หนองคาย'), ('หนองบัวลำภู', 'หนองบัวลำภู'), ('อ่างทอง', 'อ่างทอง'), ('อุดรธานี', 'อุดรธานี'), ('อุทัยธานี', 'อุทัยธานี'), ('อุตรดิตถ์', 'อุตรดิตถ์'), ('อุบลราชธานี', 'อุบลราชธานี'), ('อำนาจเจริญ', 'อำนาจเจริญ')], max_length=30, verbose_name='ภูมิลำเนาเดิม จังหวัด'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=60, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='firstname_eng',
            field=models.CharField(blank=True, max_length=30, verbose_name='ชื่อจริง(อังกฤษ)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='firstname_father_thai',
            field=models.CharField(blank=True, max_length=30, verbose_name='ชื่อจริง(ไทย)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='firstname_mother_eng',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='firstname_mother_thai',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='firstname_spouse_eng',
            field=models.CharField(blank=True, max_length=30, verbose_name='ชื่อจริงคู่สมรส(อังกฤษ)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='firstname_spouse_thai',
            field=models.CharField(blank=True, max_length=30, verbose_name='ชื่อจริงคู่สมรส(ไทย)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='firstname_thai',
            field=models.CharField(blank=True, max_length=30, verbose_name='ชื่อจริง(ไทย)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='firstnamename_father_eng',
            field=models.CharField(blank=True, max_length=30, verbose_name='ชื่อจริง(อังกฤษ)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='lastname_eng',
            field=models.CharField(blank=True, max_length=30, verbose_name='นามสกุล(อังกฤษ)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='lastname_father_eng',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='lastname_father_thai',
            field=models.CharField(blank=True, max_length=30, verbose_name='คำนำหน้า(ไทย)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='lastname_mother_eng',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='lastname_mother_thai',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='lastname_spouse_eng',
            field=models.CharField(blank=True, max_length=30, verbose_name='นามสกุลคู่สมรส(อังกฤษ)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='lastname_spouse_thai',
            field=models.CharField(blank=True, max_length=30, verbose_name='นามสกุลคู่สมรส(ไทย)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='lastname_thai',
            field=models.CharField(blank=True, max_length=30, verbose_name='นามสกุล(ไทย)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='religion',
            field=models.CharField(blank=True, choices=[('Buddha', 'พุทธ'), ('Chris', 'คริสต์'), ('Islam', 'อิสลาม'), ('Other', 'อื่นๆ')], max_length=20, verbose_name='ศาสนา'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='status',
            field=models.CharField(blank=True, choices=[('MR', 'แต่งงาน'), ('SN', 'โสด'), ('DV', 'หย่า'), ('WD', 'หม้าย')], max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='title',
            field=models.CharField(blank=True, choices=[('MR', 'Mr.(นาย)'), ('MRS', 'Mrs.(นาง)'), ('MISS', 'Miss.(นางสาว)')], max_length=6),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='academic_standing',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='academic_standing_money',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='current_position',
            field=models.CharField(blank=True, choices=[('ครูผู้ช่วย', 'ครูผู้ช่วย'), ('ครู', 'ครู'), ('รองผู้อำนวยการ', 'รองผู้อำนวยการ'), ('ผู้อำนวยการ', 'ผู้อำนวยการ')], max_length=60),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='department',
            field=models.CharField(blank=True, choices=[('ฝ่ายบริหาร', 'ฝ่ายบริหาร'), ('กลุ่มสาระการเรียนรู้วิทยาศาสตร์', 'กลุ่มสาระการเรียนรู้วิทยาศาสตร์'), ('กลุ่มสาระการเรียนรู้คณิตศาสตร์', 'กลุ่มสาระการเรียนรู้คณิตศาสตร์'), ('กลุ่มสาระการเรียนรู้ศิลปะ', 'กลุ่มสาระการเรียนรู้ศิลปะ'), ('กลุ่มสาระการเรียนรู้ภาษาไทย', 'กลุ่มสาระการเรียนรู้ภาษาไทย'), ('กลุ่มสาระการเรียนรู้ภาษาต่างประเทศ', 'กลุ่มสาระการเรียนรู้ภาษาต่างประเทศ'), ('กลุ่มสาระการเรียนรู้สังคมศึกษา ศาสนา และวัฒนธรรม', 'กลุ่มสาระการเรียนรู้สังคมศึกษา ศาสนา และวัฒนธรรม'), ('กลุ่มสาระการเรียนรู้การงานอาชีพและเทคโนโลยี', 'กลุ่มสาระการเรียนรู้การงานอาชีพและเทคโนโลยี'), ('กลุ่มสาระการเรียนรู้สุขศึกษาและพลศึกษา ', 'กลุ่มสาระการเรียนรู้สุขศึกษาและพลศึกษา ')], max_length=60),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='group',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='position',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='position_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='rank_money',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='rank_number',
            field=models.CharField(blank=True, choices=[('ค.ศ.1', 'ค.ศ.1'), ('ค.ศ.2', 'ค.ศ.2'), ('ค.ศ.3(2)', 'ค.ศ.3(2)'), ('ค.ศ.3', 'ค.ศ.3'), ('ค.ศ.4(3)', 'ค.ศ.4(3)'), ('ค.ศ.4', 'ค.ศ.4')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='subject',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
