# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20171214_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='father_title',
            field=models.CharField(blank=True, choices=[('MR', 'Mr.(นาย)')], default='MR', max_length=6),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='mother_title',
            field=models.CharField(blank=True, choices=[('MRS', 'Mrs.(นาง)'), ('MISS', 'Miss.(นางสาว)')], max_length=6),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='spouse_title',
            field=models.CharField(blank=True, choices=[('MR', 'Mr.(นาย)'), ('MRS', 'Mrs.(นาง)'), ('MISS', 'Miss.(นางสาว)')], max_length=6),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='isGPF_member',
            field=models.CharField(blank=True, choices=[('เป็น', 'เป็น'), ('ไม่เป็น', 'ไม่เป็น')], max_length=20),
        ),
    ]
