# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20171221_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInHome2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField(blank=True, max_length=1000, verbose_name='ข้อความ')),
            ],
        ),
        migrations.RemoveField(
            model_name='workinfo',
            name='group',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='image',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='workinfo',
            name='affiliation',
            field=models.CharField(blank=True, max_length=30, verbose_name='สังกัด'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=70, verbose_name='อำเภอ'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district_regis',
            field=models.CharField(blank=True, max_length=70, verbose_name='อำเภอ'),
        ),
        migrations.AlterField(
            model_name='address',
            name='lane',
            field=models.CharField(blank=True, max_length=40, verbose_name='ซอย'),
        ),
        migrations.AlterField(
            model_name='address',
            name='lane_regis',
            field=models.CharField(blank=True, max_length=40, verbose_name='ซอย'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, max_length=10, verbose_name='เลขที่'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number_regis',
            field=models.CharField(blank=True, max_length=10, verbose_name='เลขที่'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทรบ้าน'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number_regis',
            field=models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทรบ้าน'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='รหัสไปรษณีย์'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code_regis',
            field=models.CharField(blank=True, max_length=10, verbose_name='รหัสไปรษณีย์'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, choices=[('กรุงเทพมหานคร', 'กรุงเทพมหานคร'), ('กระบี่', 'กระบี่'), ('กาญจนบุรี', 'กาญจนบุรี'), ('กาฬสินธุ์', 'กาฬสินธุ์'), ('กำแพงเพชร', 'กำแพงเพชร'), ('ขอนแก่น', 'ขอนแก่น'), ('จันทบุรี', 'จันทบุรี'), ('ฉะเชิงเทรา', 'ฉะเชิงเทรา'), ('ชลบุรี', 'ชลบุรี'), ('ชัยนาท', 'ชัยนาท'), ('ชัยภูมิ', 'ชัยภูมิ'), ('ชุมพร', 'ชุมพร'), ('เชียงราย', 'เชียงราย'), ('เชียงใหม่', 'เชียงใหม่'), ('ตรัง', 'ตรัง'), ('ตราด', 'ตราด'), ('ตาก', 'ตาก'), ('นครนายก', 'นครนายก'), ('นครปฐม', 'นครปฐม'), ('นครพนม', 'นครพนม'), ('นครราชสีมา', 'นครราชสีมา'), ('นครศรีธรรมราช', 'นครศรีธรรมราช'), ('นครสวรรค์', 'นครสวรรค์'), ('นนทบุรี', 'นนทบุรี'), ('นราธิวาส', 'นราธิวาส'), ('น่าน', 'น่าน'), ('บึงกาฬ', 'บึงกาฬ'), ('บุรีรัมย์', 'บุรีรัมย์'), ('ปทุมธานี', 'ปทุมธานี'), ('ประจวบคีรีขันธ์', 'ประจวบคีรีขันธ์'), ('ปราจีนบุรี', 'ปราจีนบุรี'), ('ปัตตานี', 'ปัตตานี'), ('พระนครศรีอยุธยา', 'พระนครศรีอยุธยา'), ('พังงา', 'พังงา'), ('พัทลุง', 'พัทลุง'), ('พิจิตร', 'พิจิตร'), ('พิษณุโลก', 'พิษณุโลก'), ('เพชรบุรี', 'เพชรบุรี'), ('เพชรบูรณ์', 'เพชรบูรณ์'), ('แพร่', 'แพร่'), ('พะเยา', 'พะเยา'), ('ภูเก็ต', 'ภูเก็ต'), ('มหาสารคาม', 'มหาสารคาม'), ('มุกดาหาร', 'มุกดาหาร'), ('แม่ฮ่องสอน', 'แม่ฮ่องสอน'), ('ยะลา', 'ยะลา'), ('ยโสธร', 'ยโสธร'), ('ร้อยเอ็ด', 'ร้อยเอ็ด'), ('ระนอง', 'ระนอง'), ('ระยอง', 'ระยอง'), ('ราชบุรี', 'ราชบุรี'), ('ลพบุรี', 'ลพบุรี'), ('ลำปาง', 'ลำปาง'), ('ลำพูน', 'ลำพูน'), ('เลย', 'เลย'), ('ศรีสะเกษ', 'ศรีสะเกษ'), ('สกลนคร', 'สกลนคร'), ('สงขลา', 'สงขลา'), ('สตูล', 'สตูล'), ('สมุทรปราการ', 'สมุทรปราการ'), ('สมุทรสงคราม', 'สมุทรสงคราม'), ('สมุทรสาคร', 'สมุทรสาคร'), ('สระแก้ว', 'สระแก้ว'), ('สระบุรี', 'สระบุรี'), ('สิงห์บุรี', 'สิงห์บุรี'), ('สุโขทัย', 'สุโขทัย'), ('สุพรรณบุรี', 'สุพรรณบุรี'), ('สุราษฎร์ธานี', 'สุราษฎร์ธานี'), ('สุรินทร์', 'สุรินทร์'), ('หนองคาย', 'หนองคาย'), ('หนองบัวลำภู', 'หนองบัวลำภู'), ('อ่างทอง', 'อ่างทอง'), ('อุดรธานี', 'อุดรธานี'), ('อุทัยธานี', 'อุทัยธานี'), ('อุตรดิตถ์', 'อุตรดิตถ์'), ('อุบลราชธานี', 'อุบลราชธานี'), ('อำนาจเจริญ', 'อำนาจเจริญ')], max_length=70, verbose_name='จังหวัด'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province_regis',
            field=models.CharField(blank=True, choices=[('กรุงเทพมหานคร', 'กรุงเทพมหานคร'), ('กระบี่', 'กระบี่'), ('กาญจนบุรี', 'กาญจนบุรี'), ('กาฬสินธุ์', 'กาฬสินธุ์'), ('กำแพงเพชร', 'กำแพงเพชร'), ('ขอนแก่น', 'ขอนแก่น'), ('จันทบุรี', 'จันทบุรี'), ('ฉะเชิงเทรา', 'ฉะเชิงเทรา'), ('ชลบุรี', 'ชลบุรี'), ('ชัยนาท', 'ชัยนาท'), ('ชัยภูมิ', 'ชัยภูมิ'), ('ชุมพร', 'ชุมพร'), ('เชียงราย', 'เชียงราย'), ('เชียงใหม่', 'เชียงใหม่'), ('ตรัง', 'ตรัง'), ('ตราด', 'ตราด'), ('ตาก', 'ตาก'), ('นครนายก', 'นครนายก'), ('นครปฐม', 'นครปฐม'), ('นครพนม', 'นครพนม'), ('นครราชสีมา', 'นครราชสีมา'), ('นครศรีธรรมราช', 'นครศรีธรรมราช'), ('นครสวรรค์', 'นครสวรรค์'), ('นนทบุรี', 'นนทบุรี'), ('นราธิวาส', 'นราธิวาส'), ('น่าน', 'น่าน'), ('บึงกาฬ', 'บึงกาฬ'), ('บุรีรัมย์', 'บุรีรัมย์'), ('ปทุมธานี', 'ปทุมธานี'), ('ประจวบคีรีขันธ์', 'ประจวบคีรีขันธ์'), ('ปราจีนบุรี', 'ปราจีนบุรี'), ('ปัตตานี', 'ปัตตานี'), ('พระนครศรีอยุธยา', 'พระนครศรีอยุธยา'), ('พังงา', 'พังงา'), ('พัทลุง', 'พัทลุง'), ('พิจิตร', 'พิจิตร'), ('พิษณุโลก', 'พิษณุโลก'), ('เพชรบุรี', 'เพชรบุรี'), ('เพชรบูรณ์', 'เพชรบูรณ์'), ('แพร่', 'แพร่'), ('พะเยา', 'พะเยา'), ('ภูเก็ต', 'ภูเก็ต'), ('มหาสารคาม', 'มหาสารคาม'), ('มุกดาหาร', 'มุกดาหาร'), ('แม่ฮ่องสอน', 'แม่ฮ่องสอน'), ('ยะลา', 'ยะลา'), ('ยโสธร', 'ยโสธร'), ('ร้อยเอ็ด', 'ร้อยเอ็ด'), ('ระนอง', 'ระนอง'), ('ระยอง', 'ระยอง'), ('ราชบุรี', 'ราชบุรี'), ('ลพบุรี', 'ลพบุรี'), ('ลำปาง', 'ลำปาง'), ('ลำพูน', 'ลำพูน'), ('เลย', 'เลย'), ('ศรีสะเกษ', 'ศรีสะเกษ'), ('สกลนคร', 'สกลนคร'), ('สงขลา', 'สงขลา'), ('สตูล', 'สตูล'), ('สมุทรปราการ', 'สมุทรปราการ'), ('สมุทรสงคราม', 'สมุทรสงคราม'), ('สมุทรสาคร', 'สมุทรสาคร'), ('สระแก้ว', 'สระแก้ว'), ('สระบุรี', 'สระบุรี'), ('สิงห์บุรี', 'สิงห์บุรี'), ('สุโขทัย', 'สุโขทัย'), ('สุพรรณบุรี', 'สุพรรณบุรี'), ('สุราษฎร์ธานี', 'สุราษฎร์ธานี'), ('สุรินทร์', 'สุรินทร์'), ('หนองคาย', 'หนองคาย'), ('หนองบัวลำภู', 'หนองบัวลำภู'), ('อ่างทอง', 'อ่างทอง'), ('อุดรธานี', 'อุดรธานี'), ('อุทัยธานี', 'อุทัยธานี'), ('อุตรดิตถ์', 'อุตรดิตถ์'), ('อุบลราชธานี', 'อุบลราชธานี'), ('อำนาจเจริญ', 'อำนาจเจริญ')], max_length=70, verbose_name='จังหวัด'),
        ),
        migrations.AlterField(
            model_name='address',
            name='road',
            field=models.CharField(blank=True, max_length=70, verbose_name='ถนน'),
        ),
        migrations.AlterField(
            model_name='address',
            name='road_regis',
            field=models.CharField(blank=True, max_length=70, verbose_name='ถนน'),
        ),
        migrations.AlterField(
            model_name='address',
            name='smartphone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='เบอร์มือถือ'),
        ),
        migrations.AlterField(
            model_name='address',
            name='smartphone_number_regis',
            field=models.CharField(blank=True, max_length=20, verbose_name='เบอร์มือถือ'),
        ),
        migrations.AlterField(
            model_name='address',
            name='sub_district',
            field=models.CharField(blank=True, max_length=70, verbose_name='ตำบล'),
        ),
        migrations.AlterField(
            model_name='address',
            name='sub_district_regis',
            field=models.CharField(blank=True, max_length=70, verbose_name='ตำบล'),
        ),
        migrations.AlterField(
            model_name='address',
            name='village_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='หมู่บ้าน'),
        ),
        migrations.AlterField(
            model_name='address',
            name='village_name_regis',
            field=models.CharField(blank=True, max_length=40, verbose_name='หมู่บ้าน'),
        ),
        migrations.AlterField(
            model_name='address',
            name='village_no',
            field=models.CharField(blank=True, max_length=10, verbose_name='หมู่'),
        ),
        migrations.AlterField(
            model_name='address',
            name='village_no_regis',
            field=models.CharField(blank=True, max_length=10, verbose_name='หมู่'),
        ),
        migrations.AlterField(
            model_name='education',
            name='acronym_bachelor',
            field=models.CharField(blank=True, max_length=10, verbose_name='อักษรย่อ'),
        ),
        migrations.AlterField(
            model_name='education',
            name='acronym_master',
            field=models.CharField(blank=True, max_length=10, verbose_name='อักษรย่อ'),
        ),
        migrations.AlterField(
            model_name='education',
            name='acronym_phD',
            field=models.CharField(blank=True, max_length=10, verbose_name='อักษรย่อ'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year_bachelor',
            field=models.DateField(blank=True, null=True, verbose_name='ปีที่สำเร็จการศึกษา'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year_master',
            field=models.DateField(blank=True, null=True, verbose_name='ปีที่สำเร็จการศึกษา'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year_phD',
            field=models.DateField(blank=True, null=True, verbose_name='ปีที่สำเร็จการศึกษา'),
        ),
        migrations.AlterField(
            model_name='education',
            name='major_field_bachelor',
            field=models.CharField(blank=True, max_length=40, verbose_name='สาขาวิชาเอก'),
        ),
        migrations.AlterField(
            model_name='education',
            name='major_field_master',
            field=models.CharField(blank=True, max_length=40, verbose_name='สาขาวิชาเอก'),
        ),
        migrations.AlterField(
            model_name='education',
            name='major_field_phD',
            field=models.CharField(blank=True, max_length=40, verbose_name='สาขาวิชาเอก'),
        ),
        migrations.AlterField(
            model_name='education',
            name='minor_field_bachelor',
            field=models.CharField(blank=True, max_length=40, verbose_name='สาขาวิชาโท'),
        ),
        migrations.AlterField(
            model_name='education',
            name='minor_field_master',
            field=models.CharField(blank=True, max_length=40, verbose_name='สาขาวิชาโท'),
        ),
        migrations.AlterField(
            model_name='education',
            name='minor_field_phD',
            field=models.CharField(blank=True, max_length=40, verbose_name='สาขาวิชาโท'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year_bachelor',
            field=models.DateField(blank=True, null=True, verbose_name='ปีที่เริ่มศึกษา'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year_master',
            field=models.DateField(blank=True, null=True, verbose_name='ปีที่เริ่มศึกษา'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year_phD',
            field=models.DateField(blank=True, null=True, verbose_name='ปีที่เริ่มศึกษา'),
        ),
        migrations.AlterField(
            model_name='education',
            name='university_bachelor',
            field=models.CharField(blank=True, default='', max_length=70, verbose_name='สถาบัน'),
        ),
        migrations.AlterField(
            model_name='education',
            name='university_master',
            field=models.CharField(blank=True, default='', max_length=70, verbose_name='สถาบัน'),
        ),
        migrations.AlterField(
            model_name='education',
            name='university_phD',
            field=models.CharField(blank=True, default='', max_length=70, verbose_name='สถาบัน'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='father_title',
            field=models.CharField(blank=True, choices=[('MR', 'Mr.(นาย)')], default='MR', max_length=6, verbose_name='คำนำหน้าชื่อ'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='firstname_eng',
            field=models.CharField(blank=True, max_length=30, verbose_name='ชื่อจริง(English)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='firstname_mother_eng',
            field=models.CharField(blank=True, max_length=30, verbose_name='ชื่อจริง(English)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='firstname_mother_thai',
            field=models.CharField(blank=True, max_length=30, verbose_name='ชื่อจริง(ไทย)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='firstname_spouse_eng',
            field=models.CharField(blank=True, max_length=30, verbose_name='ชื่อจริง(English)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='firstname_spouse_thai',
            field=models.CharField(blank=True, max_length=30, verbose_name='ชื่อจริง(ไทย)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='firstnamename_father_eng',
            field=models.CharField(blank=True, max_length=30, verbose_name='ชื่อจริง(English)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='lastname_eng',
            field=models.CharField(blank=True, max_length=30, verbose_name='นามสกุล(English)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='lastname_father_eng',
            field=models.CharField(blank=True, max_length=30, verbose_name='นามสกุล(English)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='lastname_father_thai',
            field=models.CharField(blank=True, max_length=30, verbose_name='นามสกุล(ไทย)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='lastname_mother_eng',
            field=models.CharField(blank=True, max_length=30, verbose_name='นามสกุล(English)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='lastname_mother_thai',
            field=models.CharField(blank=True, max_length=30, verbose_name='นามสกุล(ไทย)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='lastname_spouse_eng',
            field=models.CharField(blank=True, max_length=30, verbose_name='นามสกุล(English)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='lastname_spouse_thai',
            field=models.CharField(blank=True, max_length=30, verbose_name='นามสกุล(ไทย)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='mother_title',
            field=models.CharField(blank=True, choices=[('MRS', 'Mrs.(นาง)'), ('MISS', 'Miss.(นางสาว)')], max_length=6, verbose_name='คำนำหน้าชื่อ'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='spouse_title',
            field=models.CharField(blank=True, choices=[('MR', 'Mr.(นาย)'), ('MRS', 'Mrs.(นาง)'), ('MISS', 'Miss.(นางสาว)')], max_length=6, verbose_name='คำนำหน้าชื่อ'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='title',
            field=models.CharField(blank=True, choices=[('MR', 'Mr.(นาย)'), ('MRS', 'Mrs.(นาง)'), ('MISS', 'Miss.(นางสาว)')], max_length=6, verbose_name='คำนำหน้าชื่อ'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='academic_standing',
            field=models.CharField(blank=True, max_length=20, verbose_name='วิทยฐานะ'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='academic_standing_money',
            field=models.IntegerField(blank=True, default=0, verbose_name='เงินวิทยฐานะ'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='current_position',
            field=models.CharField(blank=True, choices=[('ครูผู้ช่วย', 'ครูผู้ช่วย'), ('ครู', 'ครู'), ('รองผู้อำนวยการ', 'รองผู้อำนวยการ'), ('ผู้อำนวยการ', 'ผู้อำนวยการ')], max_length=60, verbose_name='ตำแหน่งปัจจุบัน'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='department',
            field=models.CharField(blank=True, choices=[('ฝ่ายบริหาร', 'ฝ่ายบริหาร'), ('กลุ่มสาระการเรียนรู้วิทยาศาสตร์', 'กลุ่มสาระการเรียนรู้วิทยาศาสตร์'), ('กลุ่มสาระการเรียนรู้คณิตศาสตร์', 'กลุ่มสาระการเรียนรู้คณิตศาสตร์'), ('กลุ่มสาระการเรียนรู้ศิลปะ', 'กลุ่มสาระการเรียนรู้ศิลปะ'), ('กลุ่มสาระการเรียนรู้ภาษาไทย', 'กลุ่มสาระการเรียนรู้ภาษาไทย'), ('กลุ่มสาระการเรียนรู้ภาษาต่างประเทศ', 'กลุ่มสาระการเรียนรู้ภาษาต่างประเทศ'), ('กลุ่มสาระการเรียนรู้สังคมศึกษา ศาสนา และวัฒนธรรม', 'กลุ่มสาระการเรียนรู้สังคมศึกษา ศาสนา และวัฒนธรรม'), ('กลุ่มสาระการเรียนรู้การงานอาชีพและเทคโนโลยี', 'กลุ่มสาระการเรียนรู้การงานอาชีพและเทคโนโลยี'), ('กลุ่มสาระการเรียนรู้สุขศึกษาและพลศึกษา', 'กลุ่มสาระการเรียนรู้สุขศึกษาและพลศึกษา')], max_length=60, verbose_name='กลุ่มสาระ'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='end_service_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันเกษียณอายุราชการ'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='isGPF_member',
            field=models.CharField(blank=True, choices=[('เป็น', 'เป็น'), ('ไม่เป็น', 'ไม่เป็น')], max_length=20, verbose_name='สมาชิก กบข.'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='position',
            field=models.CharField(blank=True, max_length=30, verbose_name='ตำแหน่ง'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='position_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='เลขที่ตำแหน่ง'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='rank_money',
            field=models.IntegerField(blank=True, default=0, verbose_name='ขั้น'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='rank_number',
            field=models.CharField(blank=True, choices=[('ค.ศ.1', 'ค.ศ.1'), ('ค.ศ.2', 'ค.ศ.2'), ('ค.ศ.3(2)', 'ค.ศ.3(2)'), ('ค.ศ.3', 'ค.ศ.3'), ('ค.ศ.4(3)', 'ค.ศ.4(3)'), ('ค.ศ.4', 'ค.ศ.4')], max_length=20, verbose_name='อันดับ'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='start_PW_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่ดำรงตำแหน่งที่โรงเรียนปทุมวิไล'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='start_service_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันเข้ารับราชการ'),
        ),
        migrations.AlterField(
            model_name='workinfo',
            name='subject',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='วิชาที่สอน'),
        ),
    ]
