# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 07:09
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20180102_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='acronym_phD',
            new_name='acronym_phd',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='end_year_phD',
            new_name='end_year_phd',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='major_field_phD',
            new_name='major_field_phd',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='minor_field_phD',
            new_name='minor_field_phd',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='start_year_phD',
            new_name='start_year_phd',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='university_phD',
            new_name='university_phd',
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='image',
            field=models.FileField(blank=True, upload_to=data.models.user_directory_path),
        ),
    ]
