# Generated by Django 2.0.6 on 2018-06-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20180104_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_year_bachelor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ปีที่สำเร็จการศึกษา'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year_master',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ปีที่สำเร็จการศึกษา'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year_phd',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ปีที่สำเร็จการศึกษา'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year_bachelor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ปีที่เริ่มศึกษา'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year_master',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ปีที่เริ่มศึกษา'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year_phd',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ปีที่เริ่มศึกษา'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='father_title',
            field=models.CharField(blank=True, choices=[('Mr.(นาย)', 'Mr.(นาย)')], default='MR', max_length=15, verbose_name='คำนำหน้าชื่อ'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='mother_title',
            field=models.CharField(blank=True, choices=[('Mrs.(นาง)', 'Mrs.(นาง)'), ('Miss.(นางสาว)', 'Miss.(นางสาว)')], max_length=15, verbose_name='คำนำหน้าชื่อ'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='religion',
            field=models.CharField(blank=True, choices=[('พุทธ', 'พุทธ'), ('คริสต์', 'คริสต์'), ('อิสลาม', 'อิสลาม'), ('อื่นๆ', 'อื่นๆ')], max_length=20, verbose_name='ศาสนา'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='spouse_title',
            field=models.CharField(blank=True, choices=[('Mr.(นาย)', 'Mr.(นาย)'), ('Mrs.(นาง)', 'Mrs.(นาง)'), ('Miss.(นางสาว)', 'Miss.(นางสาว)')], max_length=15, verbose_name='คำนำหน้าชื่อ'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='status',
            field=models.CharField(blank=True, choices=[('แต่งงาน', 'แต่งงาน'), ('โสด', 'โสด'), ('หย่า', 'หย่า'), ('หม้าย', 'หม้าย')], max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.(นาย)', 'Mr.(นาย)'), ('Mrs.(นาง)', 'Mrs.(นาง)'), ('Miss.(นางสาว)', 'Miss.(นางสาว)')], max_length=15, verbose_name='คำนำหน้าชื่อ'),
        ),
    ]
